# Base image elixir
FROM elixir:1.4.4

# install hex package manager
RUN mix local.hex --force

# create app folder
RUN mkdir /app
COPY . /app
WORKDIR /app

# install dependencies
RUN mix deps.get
RUN mix local.rebar --force

# run phoenix in *dev* mode on port 4000
CMD mix phoenix.server