# Base image elixir
FROM elixir:1.6.4

# install hex package manager
RUN mix local.hex --force
RUN mix local.rebar --force

# create app folder
RUN mkdir /app
COPY dep /app
WORKDIR /app

# install dependencies
RUN mix deps.get

# run phoenix in *dev* mode on port 4000
CMD mix phx.server